# fly.toml app configuration file generated for fly-starter-1-frontend on 2026-05-21T12:55:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-starter-1-frontend'
primary_region = 'ams'

[build]

[build.args]
VITE_BACKEND_URL = "https://fly-starter-1-backend.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
